{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eni_exporter.serviceAccountName" . }}
  namespace: {{.Release.Namespace }}
  labels:
{{ include "eni_exporter.labels" . | indent 4 }}
{{- end -}}
